site_name: "GetAddress API Documentation"
theme:
  name: "material"

nav:
  - Home: index.md
  - Endpoints: endpoints.md
  - Data Source: source.md

repo_url: "https://github.com/majidalavizadeh/getaddress-api-doc"
edit_uri: "edit/main/docs/"
