site_name: "GetAddress API Documentation"
site_url: "https://majidalavizadeh.github.io/getaddress-api-doc/"
site_dir: "site"
theme:
  name: "material"

nav:
  - Home: index.md
  - API Endpoints: endpoints.md
  - Data Source: source.md

repo_url: "https://github.com/majidalavizadeh/getaddress-api-doc"
edit_uri: "edit/main/docs/"
